{{- if .Values.brokerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-broker-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-broker-token-key": {{ .Values.brokerToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.scmToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.scmToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.bitbucketPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.bitbucketPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.azureReposToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.azureReposToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.jiraPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.jiraPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.crPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crPassword | b64enc | quote }}
---
{{- end }}
{{- if .Values.crToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scmType}}-token-{{ .Values.number}}
type: Opaque
data:
  "{{ .Values.scmType}}-token-key": {{ .Values.crToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.snykToken }}
apiVersion: v1
kind: Secret
metadata:
  name: snyk-token-{{ .Values.number}}
type: Opaque
data:
  "snyk-token-key": {{ .Values.snykToken | b64enc | quote }}
---
{{- end }}
{{- if .Values.baseNexusUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-base-nexus-url-{{ .Values.number}}
type: Opaque
data:
  "nexus-base-nexus-url": {{ .Values.baseNexusUrl | b64enc | quote }}
---
{{- end}}
{{- if .Values.nexusUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus-nexus-url-{{ .Values.number}}
type: Opaque
data:
  "nexus-nexus-url": {{ .Values.nexusUrl | b64enc | quote }}
{{- end}}
